### ISSUE TITLE
API route upload

### ISSUE THREAD

**Issue by yPiuro** [l2dit/NotesRUs#2]
## API route: **api/notes/upload**

**Will accept a file, generate a `file ID` and store the file on disk for now (not just the raw file) response includes status code and `file ID` if succesful, after MVP this take will be priority changed back to TODO. for more work**

**After MVP I will assign @Notliam99 to do the DATABASE side of the route.**

### Tasks
- [x] API Route file/download.
- [x] API Route file/upload.
- [x] Modulerize Backend.
- [x] Modulerize Responses in Backend.
- [ ] Swagger UI is properly setup.
- [x] CORS Is properly set up.

**Comment by Notliam99** [comment]
Database, if possible, will be included in the MVP

**Comment by Notliam99** [comment]
It is my second priority.

**Comment by yPiuro** [comment]
![image](https://github.com/l2dit/NotesRUs/assets/95382758/64808c76-a823-4be8-a996-b18b8c5ab6ac)

Works fine on CURL/BROWSER

Swagger UI breaks the "upload" route tho

I will open a issue and assign @Notliam99 and @yPiuro to this bug, but other than that

- [ ] API Route file/download.
- [ ] API Route file/upload.
- [ ] Modulerize Backend.
- [ ] Modulerize Responses in Backend.
- [ ] Swagger UI is properly setup.
- [ ] CORS Is properly set up.
