### ISSUE TITLE
Upload/Download Button

### ISSUE THREAD

**Issue by Ellozac** [l2dit/NotesRUs#20]
### tasks
- [x] move to Vue.js `This has been done to simplify the development prosess.`
- [x] read file contents
- [x] upload to API route
- [x] get file from api
- [x] save file

**Comment by Notliam99** [comment]
get file value from input type=file leptos\

In Leptos, you can get the file value from an input type=“file” element using the NodeRef and files() method. Here’s an example:

let input_element: NodeRef = create_node_ref();
let files = input_element.files();
 

This will give you a FileList object containing the selected files. You can then access the first file using files[0].

If you want to get the file value as a string, you can use the getAsFile() method:

let file = files[0].getAsFile();
let file_value = file.value();
 

This will give you the file value as a string.

Alternatively, you can use the FileReader API to read the file contents:

let file = files[0];
let reader = new FileReader();
reader.onload = |event| {
    let file_value = event.target.result;
    // Do something with the file value
};
reader.readAsDataURL(file);
 

Note that the files() method returns a FileList object, which is a list of File objects. Each File object has a getAsFile() method that returns the file value as a string.

Also, keep in mind that the files() method returns None if no file is selected, so you should check for this before trying to access the file value.

I hope this helps! Let me know if you have any further questions.
AI-generated answer. Please verify critical facts. [Learn more](https://search.brave.com/help/ai)

**Comment by Notliam99** [comment]
We have moved to Vue for the mean time, pushing back on a rust frontend.

**Comment by Notliam99** [comment]
@Ellozac missing code on git ref `/notes-r-us-ui/src` is missing
