### ISSUE TITLE
Docker Action

### ISSUE THREAD

**Issue by Notliam99** [l2dit/NotesRUs#30]
# Action Is Messed Up
The action I wrote is not very preformat to say the least. So we going to fix it.

## Tasks
- [x] write new docker files for Vue
- [x] write a new GitHub build
- [x] test the Dockerfiles
- [x] Document it all

**Comment by Notliam99** [comment]
Fix the NPM section

**Comment by Notliam99** [comment]
Wrong NPM command
