### ISSUE TITLE
OTP Codes Database Addition

### ISSUE THREAD

**Issue by Notliam99** [l2dit/NotesRUs#92]
# Adding OTP Codes
Have completed the schema design [HERE](https://dbdocs.io/21ltietjens/Notes-R-Us?table=one_time_codes&schema=public&view=table_structure), this allows the restoring of lost accounts through recovery codes and the sharing of accounts between devices through temporary codes.

## Tasks
- [x] Add The Table To The Schema Migrations.
- [x] Update The `.dbml` File.
- [x] Update The Entities.
